---
collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: community.libvirt
  - name: vmware.vmware
  - name: vmware.vmware_rest
  - name: nutanix.ncp
  - name: community.windows